blank_issues_enabled: false
contact_links:
  - name: 🤔 General or Open Discussions
    url: https://github.com/orgs/archetype-pal/discussions
    about: Ask general questions or start discussions here.
